---
- name: Provision Minikube Cluster
  hosts: 100.26.44.96
  become: true
  tasks:
    - name: Install prerequisites
      package:
        name:
          - curl
          - apt-transport-https
          - virtualbox  # You can use other drivers based on your setup
        state: present

    - name: Install Minikube
      command: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      register: minikube_download

    - name: Download cri-dockerd package
      get_url:
        url: "https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.13/cri-dockerd_0.3.13.3-0.ubuntu-jammy_amd64.deb"
        dest: "/tmp/cri-dockerd_0.3.13.3-0.ubuntu-jammy_amd64.deb"

    - name: Install cri-dockerd package
      apt:
        deb: "/tmp/cri-dockerd_0.3.13.3-0.ubuntu-jammy_amd64.deb"
      become: yes

    - name: Make Minikube executable
      command: chmod +x ./minikube

    - name: Move Minikube to /usr/local/bin
      command: mv ./minikube /usr/local/bin/

    - name: Start Minikube
      command: "minikube start --driver=docker"
